version: "3"

services:
  web:
    build: src/.
    ports:
      - "3000:3000"
      - "5859:5859"
    volumes:
      - ./:/queuebull
    networks:
      - queue-network
    working_dir: /queuebull
    command: sh -c "npm install && cd src && nodemon index.js"
    depends_on:
      - redis
    container_name: web
  redis:
    build: redis/.
    ports:
      - "6379:6379"
    networks:
      - queue-network
    container_name: redis
  nginx:
    container_name: nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build: ./nginx
    ports:
      - 80:80

networks:
  queue-network:
    driver: bridge
